name: build

on: push

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          docker build --tag koobson/kotbot:$SHORT_SHA --tag koobson/kotbot:latest --build-arg COMMIT_HASH=$SHORT_SHA .
      - name: push image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username koobson --password-stdin 
          docker push -a koobson/kotbot